const SURFACE_TOKENS = {
  CARD: "bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-3xl shadow-sm dark:shadow-none",
  ITEM: "rounded-lg lg:rounded-xl text-neutral-600 dark:text-neutral-400 hover:text-indigo-600 dark:hover:text-white hover:bg-indigo-50/50 dark:hover:bg-neutral-800",
  CONTROL_TRACK: "bg-neutral-100 dark:bg-neutral-800 rounded-lg p-0.5 flex items-center gap-0.5 shrink-0",
  CONTROL_BTN: "rounded-md text-xs leading-none transition-all cursor-pointer w-12 h-7 lg:w-11 lg:h-6 flex items-center justify-center shrink-0"
};

const APP_LAYOUT = {
  shell: "relative max-w-[1600px] min-h-screen h-full lg:h-screen lg:overflow-hidden mx-auto px-4 lg:px-6 xl:px-8 w-full flex flex-col lg:grid lg:grid-cols-[240px_1fr] xl:grid-cols-[280px_1fr] gap-6 xl:gap-8 pt-4 pb-8 lg:py-8 text-neutral-800 dark:text-neutral-200 selection:bg-indigo-500/10 selection:text-indigo-500 font-sans antialiased",
  main: "w-full min-w-0 mt-20 lg:mt-0 lg:h-full flex flex-col",
  pageSurface: `${SURFACE_TOKENS.CARD} flex-grow p-6 xl:p-8 lg:h-[calc(100vh-4rem)] lg:overflow-y-auto`
};

const NAVIGATION_LAYOUT = {
  sidebar: `border border-neutral-200 dark:border-neutral-800 rounded-3xl shadow-sm dark:shadow-none bg-white/75 dark:bg-neutral-900/75 backdrop-blur-md lg:bg-white lg:dark:bg-neutral-900 lg:backdrop-blur-none transition-colors duration-300 fixed inset-x-4 top-4 lg:sticky lg:inset-auto lg:top-8 lg:w-full z-[100] grid grid-cols-[auto_1fr_auto] items-center lg:flex lg:flex-col lg:items-stretch lg:justify-start px-4 py-3 lg:p-4 xl:p-6 lg:h-[calc(100vh-4rem)] lg:gap-6`,
  header: "contents lg:flex lg:flex-row lg:items-center lg:justify-between lg:w-full lg:min-w-0 lg:gap-2",
  brandButton: "w-8 h-8 rounded-full bg-indigo-600 text-white font-black text-sm flex items-center justify-center shadow-md shadow-indigo-500/20 shrink-0",
  brandText: "font-bold tracking-tight text-neutral-800 dark:text-neutral-100 shrink-0 text-sm sm:text-base truncate",
  menuButton: "lg:hidden p-2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200 transition-colors focus:outline-none cursor-pointer row-start-1 col-start-3 justify-self-end",
  menuCollapse: "col-span-3 overflow-hidden transition-[max-height] duration-[400ms] ease-in-out lg:transition-none lg:overflow-visible lg:max-h-none lg:flex lg:flex-col lg:flex-1 lg:min-h-0",
  menuCollapseOpen: "max-h-72",
  menuCollapseClosed: "max-h-0",
  menuInner: "flex flex-col pt-4 lg:pt-2 lg:contents",
  menuNavList: "flex flex-col",
  menuItem: `${SURFACE_TOKENS.ITEM} px-2.5 py-1.5 lg:px-3 lg:py-2 xl:px-4 xl:py-2.5 text-xs lg:text-sm font-bold cursor-pointer transition-all shrink-0 w-full block whitespace-normal break-keep`,
  menuItemActive: "text-indigo-600! dark:text-white! bg-indigo-50! dark:bg-neutral-800!",
  controlTrack: SURFACE_TOKENS.CONTROL_TRACK,
  controlButtonActive: `${SURFACE_TOKENS.CONTROL_BTN} font-black bg-white dark:bg-neutral-700 text-indigo-600 dark:text-indigo-400 shadow-sm`,
  controlButtonInactive: `${SURFACE_TOKENS.CONTROL_BTN} font-bold text-neutral-400 dark:text-neutral-500 hover:text-neutral-700 dark:hover:text-neutral-300`,
  functionGroup: "flex flex-col items-stretch gap-2 w-full pt-4 mt-4 border-t border-neutral-100 dark:border-neutral-800 lg:mt-auto",
  functionBox: "flex items-center justify-between w-full px-2",
  functionTitle: "block text-[11px] font-bold text-neutral-400 dark:text-neutral-500 tracking-wider",
  logoWrap: "flex items-center gap-3",
  navIcon: "w-6 h-6",
  themeIcon: "inline-block"
};

const PROJECT_LAYOUT = {
  sectionHeader: "flex flex-col gap-4 pb-6 border-b border-neutral-100 dark:border-neutral-800/60 shrink-0",
  titleRow: "flex flex-col md:flex-row md:items-end justify-between gap-4",
  title: "text-2xl lg:text-3xl font-black text-neutral-900 dark:text-neutral-50 tracking-tight leading-snug",
  role: "text-sm font-bold text-indigo-600 dark:text-indigo-400 mt-2",
  periodBadge: "inline-flex items-center gap-1.5 text-xs font-bold text-neutral-500 dark:text-neutral-400 bg-neutral-100 dark:bg-neutral-800 px-3 py-1.5 rounded-lg shrink-0 self-start md:self-auto",
  periodIcon: "text-neutral-400 dark:text-neutral-500",
  pageContent: "flex flex-col gap-6 lg:gap-8",
  infoContent: "flex flex-col gap-3",
  techContent: "flex flex-col gap-2.5 pt-4 border-t border-neutral-100 dark:border-neutral-800/40 mt-auto",
  techHeading: "text-xs font-black text-neutral-400 dark:text-neutral-50 tracking-wider uppercase flex items-center gap-1.5",
  stackWrap: "flex flex-wrap gap-2 pt-1",
  stackBadge: "px-2.5 py-1 text-xs font-bold rounded-lg bg-indigo-50/40 dark:bg-indigo-950/20 text-indigo-600 dark:text-indigo-400 border border-indigo-100/30 dark:border-indigo-900/10",
  heroGrid: "grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6 items-stretch w-full",
  infoCard: "bg-neutral-50/50 dark:bg-neutral-800/10 border border-neutral-100 dark:border-neutral-800/40 rounded-2xl p-6 flex flex-col justify-between gap-6 h-full",
  sectionTitle: "text-base font-black text-neutral-800 dark:text-neutral-200 flex items-center gap-1.5",
  taskList: "flex flex-col gap-2.5",
  taskItem: "flex items-start gap-2 text-sm text-neutral-600 dark:text-neutral-300 leading-relaxed",
  taskIcon: "text-indigo-500 mt-1 shrink-0 stroke-[3]",
  iconPrimary: "text-indigo-500 dark:text-indigo-400",
  iconSecondary: "text-neutral-400 dark:text-neutral-500 ml-auto opacity-50",
  mockupCard: "bg-neutral-100 dark:bg-neutral-800/30 border border-neutral-200 dark:border-neutral-800 rounded-2xl overflow-hidden flex items-center justify-center p-6 lg:p-8 relative group select-none min-h-[250px] lg:min-h-auto h-full",
  mockupOverlay: "absolute inset-0 bg-[linear-gradient(to_right,#80808006_1px,transparent_1px),linear-gradient(to_bottom,#80808006_1px,transparent_1px)] bg-size-[12px_12px] dark:bg-[linear-gradient(to_right,#ffffff02_1px,transparent_1px),linear-gradient(to_bottom,#ffffff02_1px,transparent_1px)] pointer-events-none",
  imageFrame: "w-full h-auto max-w-full object-contain rounded-lg shadow-[0_12px_30px_rgba(0,0,0,0.08)] dark:shadow-[0_20px_40px_rgba(0,0,0,0.3)] transition-transform duration-500 group-hover:scale-[1.025]",
  troubleSection: "pt-6 border-t border-neutral-100 dark:border-neutral-800/80 flex flex-col gap-5 shrink-0",
  troubleSectionHeading: "text-lg font-black text-neutral-800 dark:text-neutral-200 flex items-center gap-2",
  troubleSectionIcon: "text-neutral-700 dark:text-neutral-300",
  troubleGrid: "grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6",
  troubleCard: "p-5 rounded-2xl flex flex-col gap-2.5 border transition-all duration-300",
  troubleProblem: "bg-rose-50/50 dark:bg-rose-950/10 border-rose-100 dark:border-rose-900/30",
  troubleAnalysis: "bg-amber-50/50 dark:bg-amber-950/10 border-amber-100 dark:border-amber-900/30",
  troubleSolution: "bg-indigo-50/50 dark:bg-indigo-950/10 border-indigo-100 dark:border-indigo-900/30",
  troubleResult: "bg-emerald-50/50 dark:bg-emerald-950/10 border-emerald-100 dark:border-emerald-900/30",
  troubleCardHeader: "text-sm font-bold flex items-center gap-2",
  troubleTitleProblem: "text-rose-600 dark:text-rose-400",
  troubleTitleAnalysis: "text-amber-600 dark:text-amber-400",
  troubleTitleSolution: "text-indigo-600 dark:text-indigo-400",
  troubleTitleResult: "text-emerald-600 dark:text-emerald-400",
  troubleBadge: "w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shadow-sm",
  troubleBadgeProblem: "bg-rose-100 dark:bg-rose-900/50",
  troubleBadgeAnalysis: "bg-amber-100 dark:bg-amber-900/50",
  troubleBadgeSolution: "bg-indigo-100 dark:bg-indigo-900/50",
  troubleBadgeResult: "bg-emerald-100 dark:bg-emerald-900/50",
  troubleDesc: "text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed"
};

const PROFILE_LAYOUT = {
  grid: "grid grid-cols-1 xl:grid-cols-[300px_1fr] gap-8 xl:gap-12 items-start",
  leftCol: "flex flex-col gap-8 xl:sticky xl:top-24",
  title: "text-2xl xl:text-3xl font-black tracking-tight text-neutral-900 dark:text-neutral-50",
  roleText: "text-sm font-semibold text-indigo-600 dark:text-indigo-400 mt-1.5",
  contactCard: "bg-neutral-50/50 dark:bg-neutral-800/20 border border-neutral-100 dark:border-neutral-800/50 rounded-2xl p-4 flex flex-col gap-3",
  contactTitle: "text-xs font-bold text-neutral-400 dark:text-neutral-500 tracking-wider uppercase",
  contactList: "flex flex-col gap-2.5",
  contactItem: "flex items-center gap-2.5 text-xs font-semibold text-neutral-600 dark:text-neutral-300 hover:text-indigo-600 dark:hover:text-white transition-colors",
  contactIcon: "w-4 h-4 text-neutral-500",
  stackSection: "flex flex-col gap-5",
  stackTitle: "text-xs font-bold text-neutral-400 dark:text-neutral-500 tracking-wider uppercase",
  stackGroupList: "flex flex-col gap-4",
  stackGroup: "flex flex-col gap-2",
  stackGroupTitle: "text-xs font-bold text-neutral-500 dark:text-neutral-400",
  stackBadgeWrap: "flex flex-wrap gap-1.5",
  stackBadge: "px-2 py-1 text-[11px] font-bold rounded-lg bg-indigo-50/50 dark:bg-indigo-950/20 text-indigo-600 dark:text-indigo-400 border border-indigo-100/30 dark:border-indigo-900/10",
  timelineCol: "flex flex-col gap-6 xl:border-l xl:border-neutral-100 xl:dark:border-neutral-800/60 xl:pl-8",
  timelineTitle: "text-lg font-black text-neutral-800 dark:text-neutral-200 mb-2 uppercase",
  timelineWrap: "relative ml-2 pl-6 flex flex-col gap-8",
  timelineLine: "absolute left-0 top-1.5 bottom-1.5 w-0.5 -translate-x-1/2 bg-neutral-100 dark:bg-neutral-800/80",
  timelineItem: "relative group",
  timelineDotOuter: "absolute -left-6 -translate-x-1/2 top-1.5 w-4 h-4 rounded-full bg-white dark:bg-neutral-900 border-2 border-neutral-300 dark:border-neutral-700 group-hover:border-indigo-600 dark:group-hover:border-indigo-400 transition-colors duration-300 z-10",
  timelineDotInner: "absolute top-1/2 left-1/2 w-1.5 h-1.5 rounded-full bg-neutral-200 dark:bg-neutral-800 group-hover:bg-indigo-600 dark:group-hover:bg-indigo-400 -translate-x-1/2 -translate-y-1/2 transition-colors duration-300",
  timelineHeader: "flex flex-col md:flex-row md:items-center justify-between gap-1.5",
  timelineItemTitle: "text-sm xl:text-base font-extrabold text-neutral-800 dark:text-neutral-100 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors duration-300",
  timelinePeriod: "text-[11px] md:text-xs font-bold text-neutral-400 dark:text-neutral-500 font-mono tracking-tight shrink-0 bg-neutral-100 dark:bg-neutral-800/50 px-2 py-0.5 rounded-md self-start md:self-auto",
  timelineMetaWrap: "flex flex-wrap items-center gap-2 mt-2",
  timelineRole: "text-[11px] font-bold text-neutral-500 dark:text-neutral-400 bg-neutral-50 dark:bg-neutral-800 px-2 py-0.5 rounded border border-neutral-100 dark:border-neutral-800",
  timelineStackWrap: "flex gap-1",
  timelineStackItem: "text-[10px] font-bold text-neutral-400 dark:text-neutral-500",
  timelineTaskList: "list-none flex flex-col gap-1.5 mt-3.5",
  timelineTaskItem: "text-xs text-neutral-500 dark:text-neutral-400 leading-relaxed flex items-start gap-1.5",
  timelineTaskBullet: "text-indigo-500 dark:text-indigo-400 mt-1 select-none shrink-0"
};

const FEEDBACK_LAYOUT = {
  wrapper: "text-center py-6 px-4 flex flex-col items-center",
  icon: "w-16 h-16 text-indigo-600 dark:text-indigo-400 mb-6 animate-bounce",
  title: "text-3xl font-bold text-gray-800 dark:text-gray-100 mb-4",
  description: "text-base text-gray-600 dark:text-gray-400 leading-relaxed mb-8 whitespace-pre-wrap",
  button: "bg-indigo-600 text-white font-semibold py-3 px-6 rounded-lg shadow-md transition-all duration-200 hover:bg-indigo-700 hover:-translate-y-0.5 active:translate-y-0"
};

export const STYLES = {
  // App shell
  wrapper: APP_LAYOUT.shell,
  main: APP_LAYOUT.main,
  mainCard: APP_LAYOUT.pageSurface,

  // Navigation
  nav: NAVIGATION_LAYOUT.sidebar,
  navHeader: NAVIGATION_LAYOUT.header,
  logoBtn: NAVIGATION_LAYOUT.brandButton,
  profileName: NAVIGATION_LAYOUT.brandText,
  menuButton: NAVIGATION_LAYOUT.menuButton,
  menuCollapse: NAVIGATION_LAYOUT.menuCollapse,
  menuCollapseOpen: NAVIGATION_LAYOUT.menuCollapseOpen,
  menuCollapseClosed: NAVIGATION_LAYOUT.menuCollapseClosed,
  menuInner: NAVIGATION_LAYOUT.menuInner,
  menuNavList: NAVIGATION_LAYOUT.menuNavList,
  menuItem: NAVIGATION_LAYOUT.menuItem,
  menuActive: NAVIGATION_LAYOUT.menuItemActive,
  switchBar: NAVIGATION_LAYOUT.controlTrack,
  switchBtnActive: NAVIGATION_LAYOUT.controlButtonActive,
  switchBtnInactive: NAVIGATION_LAYOUT.controlButtonInactive,
  funcGroup: NAVIGATION_LAYOUT.functionGroup,
  funcBox: NAVIGATION_LAYOUT.functionBox,
  funcTitle: NAVIGATION_LAYOUT.functionTitle,
  navLogoWrap: NAVIGATION_LAYOUT.logoWrap,
  navIcon: NAVIGATION_LAYOUT.navIcon,
  themeIcon: NAVIGATION_LAYOUT.themeIcon,

  // Project page
  projectHeaderSection: PROJECT_LAYOUT.sectionHeader,
  projectTitleRow: PROJECT_LAYOUT.titleRow,
  projectTitle: PROJECT_LAYOUT.title,
  projectRole: PROJECT_LAYOUT.role,
  projectPeriodBadge: PROJECT_LAYOUT.periodBadge,
  projectPeriodIcon: PROJECT_LAYOUT.periodIcon,
  projectPageContent: PROJECT_LAYOUT.pageContent,
  projectInfoContent: PROJECT_LAYOUT.infoContent,
  projectTechContent: PROJECT_LAYOUT.techContent,
  projectTechHeading: PROJECT_LAYOUT.techHeading,
  projectStackWrap: PROJECT_LAYOUT.stackWrap,
  projectStackBadge: PROJECT_LAYOUT.stackBadge,
  projectHeroSection: PROJECT_LAYOUT.heroGrid,
  projectContextCard: PROJECT_LAYOUT.infoCard,
  projectSecTitle: PROJECT_LAYOUT.sectionTitle,
  projectTaskList: PROJECT_LAYOUT.taskList,
  projectTaskItem: PROJECT_LAYOUT.taskItem,
  projectTaskIcon: PROJECT_LAYOUT.taskIcon,
  projectIconPrimary: PROJECT_LAYOUT.iconPrimary,
  projectIconSecondary: PROJECT_LAYOUT.iconSecondary,
  projectMockupCard: PROJECT_LAYOUT.mockupCard,
  projectMockupOverlay: PROJECT_LAYOUT.mockupOverlay,
  projectImgFixed: PROJECT_LAYOUT.imageFrame,
  troubleSection: PROJECT_LAYOUT.troubleSection,
  troubleSectionHeading: PROJECT_LAYOUT.troubleSectionHeading,
  troubleSectionIcon: PROJECT_LAYOUT.troubleSectionIcon,
  troubleGrid: PROJECT_LAYOUT.troubleGrid,
  troubleCardCommon: PROJECT_LAYOUT.troubleCard,
  troubleCardProblem: PROJECT_LAYOUT.troubleProblem,
  troubleCardAnalysis: PROJECT_LAYOUT.troubleAnalysis,
  troubleCardSolution: PROJECT_LAYOUT.troubleSolution,
  troubleCardResult: PROJECT_LAYOUT.troubleResult,
  troubleCardHeader: PROJECT_LAYOUT.troubleCardHeader,
  troubleTitleProblem: PROJECT_LAYOUT.troubleTitleProblem,
  troubleTitleAnalysis: PROJECT_LAYOUT.troubleTitleAnalysis,
  troubleTitleSolution: PROJECT_LAYOUT.troubleTitleSolution,
  troubleTitleResult: PROJECT_LAYOUT.troubleTitleResult,
  troubleBadge: PROJECT_LAYOUT.troubleBadge,
  troubleBadgeProblem: PROJECT_LAYOUT.troubleBadgeProblem,
  troubleBadgeAnalysis: PROJECT_LAYOUT.troubleBadgeAnalysis,
  troubleBadgeSolution: PROJECT_LAYOUT.troubleBadgeSolution,
  troubleBadgeResult: PROJECT_LAYOUT.troubleBadgeResult,
  troubleDesc: PROJECT_LAYOUT.troubleDesc,

  // Profile page
  profileGrid: PROFILE_LAYOUT.grid,
  profileLeftCol: PROFILE_LAYOUT.leftCol,
  profileTitle: PROFILE_LAYOUT.title,
  profileRoleText: PROFILE_LAYOUT.roleText,
  contactCard: PROFILE_LAYOUT.contactCard,
  contactTitle: PROFILE_LAYOUT.contactTitle,
  contactList: PROFILE_LAYOUT.contactList,
  contactItem: PROFILE_LAYOUT.contactItem,
  contactIcon: PROFILE_LAYOUT.contactIcon,
  stackSection: PROFILE_LAYOUT.stackSection,
  stackTitle: PROFILE_LAYOUT.stackTitle,
  stackGroupList: PROFILE_LAYOUT.stackGroupList,
  stackGroup: PROFILE_LAYOUT.stackGroup,
  stackGroupTitle: PROFILE_LAYOUT.stackGroupTitle,
  stackBadgeWrap: PROFILE_LAYOUT.stackBadgeWrap,
  profileStackBadge: PROFILE_LAYOUT.stackBadge,
  timelineCol: PROFILE_LAYOUT.timelineCol,
  timelineTitle: PROFILE_LAYOUT.timelineTitle,
  timelineWrap: PROFILE_LAYOUT.timelineWrap,
  timelineLine: PROFILE_LAYOUT.timelineLine,
  timelineItem: PROFILE_LAYOUT.timelineItem,
  timelineDotOuter: PROFILE_LAYOUT.timelineDotOuter,
  timelineDotInner: PROFILE_LAYOUT.timelineDotInner,
  timelineHeader: PROFILE_LAYOUT.timelineHeader,
  timelineItemTitle: PROFILE_LAYOUT.timelineItemTitle,
  timelinePeriod: PROFILE_LAYOUT.timelinePeriod,
  timelineMetaWrap: PROFILE_LAYOUT.timelineMetaWrap,
  timelineRole: PROFILE_LAYOUT.timelineRole,
  timelineStackWrap: PROFILE_LAYOUT.timelineStackWrap,
  timelineStackItem: PROFILE_LAYOUT.timelineStackItem,
  timelineTaskList: PROFILE_LAYOUT.timelineTaskList,
  timelineTaskItem: PROFILE_LAYOUT.timelineTaskItem,
  timelineTaskBullet: PROFILE_LAYOUT.timelineTaskBullet,

  // Error page
  errorWrapper: FEEDBACK_LAYOUT.wrapper,
  errorIcon: FEEDBACK_LAYOUT.icon,
  errorTitle: FEEDBACK_LAYOUT.title,
  errorDescription: FEEDBACK_LAYOUT.description,
  errorButton: FEEDBACK_LAYOUT.button
};